[phases.setup]
# Installeer alleen wat nodig is
packages = ["openjdk21", "nodejs"]

[phases.build]
commands = [
    "chmod +x Trivia_backend/mvnw",
    "cd Trivia_backend && ./mvnw clean package -DskipTests",
    "cd trivia-frontend && npm install && npm run build"
]

[start]
cmd = "bash start.sh"
